"use client"
import { Inter } from "next/font/google"
import "./globals.css"
import { MoralisProvider } from "react-moralis"

const inter = Inter({ subsets: ["latin"] })

/* export const metadata = {
    title: "Smart Contract Lottery FCC",
    description: "Generated by create next app",
} */

export default function RootLayout({ children }) {
    return (
        <MoralisProvider initializeOnMount={false}>
            <html lang="en">
                <head>
                    <title>Smart Contract Lottery</title>
                </head>
                <body className={inter.className}>{children}</body>
            </html>
        </MoralisProvider>
    )
}
